intern_candidate_code = {
    'ohagwugeneral@gmail.com':'GER/EDO/AN/INT/0001',
'chukwujemima1@gmail.com':'GER/EDO/AN/INT/0002',
'kanzepeters2@gmail.com':'GER/EDO/AN/INT/0003',
'victoriarichard26@gmail.com':'GER/EDO/AN/INT/0004',
'jehanmatthew1@gmail.com':'GER/EDO/AN/INT/0005',
'judeawara@gmail.com':'GER/EDO/AN/INT/0006',
'uwakwechibuike08@gmail.com':'GER/EDO/AN/INT/0007',
'nwinyiamarachukwu@gmail.com':'GER/EDO/AN/INT/0008',
'nuelodo95@gmail.com':'GER/EDO/AN/INT/0009',
'Daregold071995@gmail.com':'GER/EDO/AN/INT/OO10',
'oswardossy12@gmail.com':'GER/EDO/AN/INT/OO11',
'kalagborthankgod@gmail.com':'GER/EDO/AN/INT/OO12',
'ajsule28@gmail.com':'GER/EDO/AN/INT/OO13',
'chidiebereuwakwe91@gmail.com':'GER/EDO/AN/INT/OO14',
'perpetual.godwin@yahoo.com':'GER/EDO/AN/INT/OO15',
'ejiroederademu@gmail.com':'GER/EDO/AN/INT/OO16',
'ezemeck@gmail.com':'GER/EDO/AN/INT/OO17',
'oluwapelumiakinola@gmail.com':'GER/EDO/AN/INT/OO18',
'xcellingalways@gmail.com':'GER/EDO/AN/INT/OO19',
'Abonyi_ernest@yahoo.com':'GER/EDO/AN/INT/OO20',
'Okoliedjoel@gmail.com':'GER/EDO/AN/INT/OO21',
'egbeiyonstella@gmail.com':'GER/EDO/AN/INT/OO22',
'idioandy67@gmail.com':'GER/EDO/AN/INT/OO23',
'dbnwele@gmail.com':'GER/EDO/AN/INT/OO24',
'mathiaskennedy8@gmail.com':'GER/EDO/AN/INT/OO25',
'lovethanosike1@gmail.com':'GER/EDO/AN/INT/OO26',
'berrymedic@gmail.com':'GER/EDO/AN/INT/OO27',
'donnemario@gmail.com':'GER/EDO/AN/INT/OO28',
'apochiobed@gmail.com':'GER/EDO/AN/INT/OO29',
'iloanyajohnson@gmail.com':'GER/EDO/AN/INT/OO30',
'dinmaokani@gmail.com':'GER/EDO/AN/INT/OO31',
'inyangesther8@gmail.com':'GER/EDO/AN/INT/OO32',
'EHIEDUK@GMAIL.COM':'GER/EDO/AN/INT/OO33',
'inyangevol@gmail.com':'GER/EDO/AN/INT/OO34',
'dantiger777@gmail.com':'GER/EDO/AN/INT/OO35',
'uniquechimelin2020@gmail.com':'GER/EDO/AN/INT/OO36',
'francischimzaram2@gmail.com':'GER/EDO/AN/INT/OO37',
'ogbepriscachiamaka@gmail.com':'GER/EDO/AN/INT/OO38',
'runyinah@gmail.com':'GER/EDO/AN/INT/OO39',
'joansdesire@gmail.com':'GER/EDO/AN/INT/OO40',
'truthfulnessisimhape@gmail.com':'GER/EDO/AN/INT/OO41',
'diamondloveth3@gmail.com':'GER/EDO/AN/INT/OO42',
'Okoliemeka19@gmail.com':'GER/EDO/AN/INT/OO43',
'MRNWANKWO@YAHOO.COM':'GER/EDO/AN/INT/OO44',
'raymondking009@gmail.com':'GER/EDO/AN/INT/OO45',
'arua4blessing@gmail.com':'GER/EDO/AN/INT/OO46',
'agufrancis7@gmail.com':'GER/EDO/AN/INT/OO47',
'anachiwokingsley@gmail.com':'GER/EDO/AN/INT/OO48',
'nnamginika@gmail.com':'GER/EDO/AN/INT/OO49',
'nancydominic22@gmail.com':'GER/EDO/AN/INT/OO50',
'Sophiadefirst3@gmail.com':'GER/EDO/AN/INT/OO51',
'clintonemeka05@gmail.com':'GER/EDO/AN/INT/OO52',
'nekkykarl111@gmail.com':'GER/EDO/AN/INT/OO53',
'Ndukakuee@gmail.com':'GER/EDO/AN/INT/OO54',
'aguprincewill@gmail.com':'GER/EDO/AN/INT/OO55',
'kkalu0417@gmail.com':'GER/EDO/AN/INT/OO56',
'ositaorji55@gmail.com':'GER/EDO/AN/INT/OO57',
'ewekauwa52@gmail.com':'GER/EDO/AN/INT/OO58',
'nkchuks4@gmail.com':'GER/EDO/AN/INT/OO59',
'abrahamekpenga@gmail.com':'GER/EDO/AN/INT/OO60',
'rasheedcatherine@gmail.com':'GER/EDO/AN/INT/OO61',
'maryjaneuche51@gmail.com':'GER/EDO/AN/INT/OO62',
'glowreeisi21@gmail.com':'GER/EDO/AN/INT/OO63',
'tochysteph818@gmail.com':'GER/EDO/AN/INT/OO64',
'ninonwa154@gmail.com':'GER/EDO/AN/INT/OO65',
'vickobest97@gmail.com':'GER/EDO/AN/INT/OO66',
'ebosikha96@gmail.com':'GER/EDO/AN/INT/OO67',
'okosunmarvel25@gmail.com':'GER/EDO/AN/INT/OO68',
'chukwunovictoria@gmail.com':'GER/EDO/AN/INT/OO69',
'Anthonyoketa1@gmail.com':'GER/EDO/AN/INT/OO70',
'favouradaolisa45@gmail.com':'GER/EDO/AN/INT/OO71',
'obiuzoamaka5040@gmail.com':'GER/EDO/AN/INT/OO72',
'okohfavour11@gmail.com':'GER/EDO/AN/INT/OO73',
'charlievicks77@gmail.com':'GER/EDO/AN/INT/OO74',
'sirsamuela@gmail.com':'GER/EDO/AN/INT/OO75',
'esthernyong300@gmail.com':'GER/EDO/AN/INT/OO76',
'alagbalaayomidebukky@gmail.com':'GER/EDO/AN/INT/OO77',
'kingsleynnaji048@gmail.com':'GER/EDO/AN/INT/OO78',
'faithtoritse@gmail.com':'GER/EDO/AN/INT/OO79',
'adesanyalydia@gmail.com':'GER/EDO/AN/INT/OO80',
'lordrichado@gmail.com': 'Richard Olumide Daodu'

}
intern_first_name= {
'ohagwugeneral@gmail.com':'Anthony',
'chukwujemima1@gmail.com':'Jemima',
'kanzepeters2@gmail.com':'Peter',
'victoriarichard26@gmail.com':'Victoria',
'jehanmatthew1@gmail.com':'Matthew ',
'judeawara@gmail.com':'Jude',
'uwakwechibuike08@gmail.com':'Uwakwe',
'nwinyiamarachukwu@gmail.com':'Amarachukwu',
'nuelodo95@gmail.com':'Odo',
'Daregold071995@gmail.com':'Ezekiel ',
'oswardossy12@gmail.com':'Victory ',
'kalagborthankgod@gmail.com':'ThankGod',
'ajsule28@gmail.com':'Sule',
'chidiebereuwakwe91@gmail.com':'Chidiebere',
'perpetual.godwin@yahoo.com':'Njideka',
'ejiroederademu@gmail.com':'Ejiro',
'ezemeck@gmail.com':'Martins Chijioke',
'oluwapelumiakinola@gmail.com':'Matthew ',
'xcellingalways@gmail.com':'Victor Okechukwu',
'Abonyi_ernest@yahoo.com':'Ernest',
'Okoliedjoel@gmail.com':'Okolie',
'egbeiyonstella@gmail.com':'Stella',
'idioandy67@gmail.com':'Andy',
'dbnwele@gmail.com':'David',
'mathiaskennedy8@gmail.com':'Kennedy',
'lovethanosike1@gmail.com':'Nnenna Loveth',
'berrymedic@gmail.com':'Augustine',
'donnemario@gmail.com':'Mary',
'apochiobed@gmail.com':'Obed',
'iloanyajohnson@gmail.com':'Johnson ',
'dinmaokani@gmail.com':'Esther ',
'inyangesther8@gmail.com':'Inyang',
'EHIEDUK@GMAIL.COM':'Kennedy ',
'inyangevol@gmail.com':'Uforo',
'dantiger777@gmail.com':'Agu',
'uniquechimelin2020@gmail.com':'Precious',
'francischimzaram2@gmail.com':'Michael',
'ogbepriscachiamaka@gmail.com':'Chiamaka',
'runyinah@gmail.com':'Ruth',
'joansdesire@gmail.com':'Joan',
'truthfulnessisimhape@gmail.com':'Isimhape',
'diamondloveth3@gmail.com':'Loveth',
'Okoliemeka19@gmail.com':'Emeka',
'MRNWANKWO@YAHOO.COM':'Nnamdi',
'raymondking009@gmail.com':'Raymond',
'arua4blessing@gmail.com':'Blessing',
'agufrancis7@gmail.com':'Ikechukwu',
'anachiwokingsley@gmail.com':'Anachiwo Kingsley Ifunanya',
'nnamginika@gmail.com':'Ginika Francisca',
'nancydominic22@gmail.com':'Nancy',
'Sophiadefirst3@gmail.com':'Chinenye Sophia',
'clintonemeka05@gmail.com':'Clinton ',
'nekkykarl111@gmail.com':'Onuh',
'Ndukakuee@gmail.com':'Ndukaku Collins',
'aguprincewill@gmail.com':'Princewill',
'kkalu0417@gmail.com':'Kingsley ',
'ositaorji55@gmail.com':'Osita',
'ewekauwa52@gmail.com':'Eweka Uwa',
'nkchuks4@gmail.com':'CHUKWU',
'abrahamekpenga@gmail.com':'Abraham',
'rasheedcatherine@gmail.com':'Catherine ',
'maryjaneuche51@gmail.com':'Ogochukwu',
'glowreeisi21@gmail.com':'Glory',
'tochysteph818@gmail.com':'Prisca',
'ninonwa154@gmail.com':'Sandra',
'vickobest97@gmail.com':'Ebhomielen',
'ebosikha96@gmail.com':'Eboseremen',
'okosunmarvel25@gmail.com':'Okosun',
'chukwunovictoria@gmail.com':'Chukwuno',
'Anthonyoketa1@gmail.com':'Oketa',
'favouradaolisa45@gmail.com':'Favour',
'obiuzoamaka5040@gmail.com':'Uzoamaka',
'okohfavour11@gmail.com':'Favour ',
'charlievicks77@gmail.com':'Victor ',
'sirsamuela@gmail.com':'Ayodele',
'esthernyong300@gmail.com':'Esther',
'alagbalaayomidebukky@gmail.com':'Ayomide',
'kingsleynnaji048@gmail.com':'Kingsley ',
'faithtoritse@gmail.com':'Gbugbemi',
'adesanyalydia@gmail.com':'Moses ',
'lordrichado@gmail.com': 'Richard Olumide Daodu'


}

intern_last_name={
'ohagwugeneral@gmail.com':'Ohagwu',
'chukwujemima1@gmail.com':'Adanna Chukwu',
'kanzepeters2@gmail.com':'Ocho',
'victoriarichard26@gmail.com':'Edet',
'jehanmatthew1@gmail.com':'Egwu',
'judeawara@gmail.com':'Edu',
'uwakwechibuike08@gmail.com':'Chibuike',
'nwinyiamarachukwu@gmail.com':'Udobi',
'nuelodo95@gmail.com':'Chibuike Emmanuel',
'Daregold071995@gmail.com':'Dare',
'oswardossy12@gmail.com':'Akingbe',
'kalagborthankgod@gmail.com':'Kalagbor',
'ajsule28@gmail.com':'Audu',
'chidiebereuwakwe91@gmail.com':'Uwakwe',
'perpetual.godwin@yahoo.com':'Godwin',
'ejiroederademu@gmail.com':'Ederademu',
'ezemeck@gmail.com':'Eze',
'oluwapelumiakinola@gmail.com':'Akinola',
'xcellingalways@gmail.com':'Chimezie',
'Abonyi_ernest@yahoo.com':'Obinna',
'Okoliedjoel@gmail.com':'Dibia Joel',
'egbeiyonstella@gmail.com':'Egbeiyon',
'idioandy67@gmail.com':'Idio',
'dbnwele@gmail.com':'Nwele',
'mathiaskennedy8@gmail.com':'Ebhojaye',
'lovethanosike1@gmail.com':'Anosike',
'berrymedic@gmail.com':'Chukwusa',
'donnemario@gmail.com':'Eyo II',
'apochiobed@gmail.com':'Apochi',
'iloanyajohnson@gmail.com':'Ekene',
'dinmaokani@gmail.com':'Okani',
'inyangesther8@gmail.com':'Esther ',
'EHIEDUK@GMAIL.COM':'Ugboko',
'inyangevol@gmail.com':'Offiong',
'dantiger777@gmail.com':'Daniel',
'uniquechimelin2020@gmail.com':'Chimeladu Precious',
'francischimzaram2@gmail.com':'Francis Chimzaram',
'ogbepriscachiamaka@gmail.com':'Ogbe',
'runyinah@gmail.com':'Onoi',
'joansdesire@gmail.com':'Ihenacho',
'truthfulnessisimhape@gmail.com':'Truthfulness ',
'diamondloveth3@gmail.com':'Nwankwo',
'Okoliemeka19@gmail.com':'Okoli',
'MRNWANKWO@YAHOO.COM':'Nwankwo',
'raymondking009@gmail.com':'Sylvanus',
'arua4blessing@gmail.com':'Arua',
'agufrancis7@gmail.com':'Agu',
'anachiwokingsley@gmail.com':'Anachiwo',
'nnamginika@gmail.com':'Nnam',
'nancydominic22@gmail.com':'Ogbidi',
'Sophiadefirst3@gmail.com':'Nwankwo',
'clintonemeka05@gmail.com':'Ogayi',
'nekkykarl111@gmail.com':'Calister Nneka',
'Ndukakuee@gmail.com':'Enogu Esomchi',
'aguprincewill@gmail.com':'Agu',
'kkalu0417@gmail.com':'Kalu',
'ositaorji55@gmail.com':'Orji',
'ewekauwa52@gmail.com':'Osaruehiamen',
'nkchuks4@gmail.com':'MARY.N.',
'abrahamekpenga@gmail.com':'Ekpenga',
'rasheedcatherine@gmail.com':'Rasheed',
'maryjaneuche51@gmail.com':'Uche',
'glowreeisi21@gmail.com':'Ibhafidon',
'tochysteph818@gmail.com':'IWUCHUKWU',
'ninonwa154@gmail.com':'Chukwu',
'vickobest97@gmail.com':'Victor Oseremen',
'ebosikha96@gmail.com':'Ikharebhore',
'okosunmarvel25@gmail.com':'Marvel',
'chukwunovictoria@gmail.com':'Victoria ',
'Anthonyoketa1@gmail.com':'Anthony ',
'favouradaolisa45@gmail.com':'Nwachukwu',
'obiuzoamaka5040@gmail.com':'Obi',
'okohfavour11@gmail.com':'Okoh',
'charlievicks77@gmail.com':'Okoli',
'sirsamuela@gmail.com':'Atoyebi',
'esthernyong300@gmail.com':'Etim',
'alagbalaayomidebukky@gmail.com':'Alagbala',
'kingsleynnaji048@gmail.com':'Nnaji',
'faithtoritse@gmail.com':'Toritsemotse',
'adesanyalydia@gmail.com':'Damilola Adesanya',
'lordrichado@gmail.com': 'Richard Olumide Daodu',

}