# Generated by Django 3.1 on 2020-08-25 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200825_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.AddField(
            model_name='questions',
            name='candidate_code',
            field=models.CharField(default='GER/EDO/AN/INT/00', max_length=200),
        ),
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 24, 5, 187400, tzinfo=utc)),
        ),
    ]
