# Generated by Django 3.1 on 2020-08-25 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20200825_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.questionforcandidate'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 1, 17, 420534, tzinfo=utc)),
        ),
    ]
