# Generated by Django 3.1 on 2020-10-01 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200825_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 4, 42, 12, 654635, tzinfo=utc)),
        ),
    ]
