# Generated by Django 3.1 on 2020-10-06 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20201001_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 7, 50, 10, 450867, tzinfo=utc)),
        ),
    ]
