# Generated by Django 3.1 on 2020-10-06 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20201006_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 7, 58, 34, 107345, tzinfo=utc)),
        ),
    ]
