# Generated by Django 3.1 on 2020-08-25 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 33, 5, 606516, tzinfo=utc)),
        ),
    ]
