# Generated by Django 3.1 on 2020-08-25 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20200825_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 35, 21, 768624, tzinfo=utc)),
        ),
    ]
