# Generated by Django 3.1 on 2020-08-25 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0005_auto_20200825_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='deadline',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 56, 53, 150274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='author',
            field=models.ForeignKey(blank=True, default='accounts.CustomUser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
