# Generated by Django 3.1 on 2020-08-25 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20200825_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 17, 56, 507880, tzinfo=utc)),
        ),
    ]
