# Generated by Django 3.1 on 2020-08-25 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_auto_20200825_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 29, 13, 474711, tzinfo=utc)),
        ),
    ]
