# Generated by Django 3.1 on 2020-08-25 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_auto_20200825_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 16, 35, 201158, tzinfo=utc)),
        ),
    ]
