# Generated by Django 3.1 on 2020-10-06 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0019_auto_20201001_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 7, 50, 10, 447665, tzinfo=utc)),
        ),
    ]
